name: greatr
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  algolia: ^1.0.2
  anim_search_bar: ^2.0.2
  awesome_notifications: ^0.0.6+10
  bubble: ^1.2.1
  cached_network_image: ^3.1.0
  carousel_slider: ^4.0.0
  cloud_firestore: ^2.5.2
  concentric_transition: ^1.0.1
  cupertino_icons: ^1.0.2
  date_format: ^2.0.4
  extended_image:
    git:
      url: https://github.com/fluttercandies/extended_image.git
      ref: 47def694fd10481d725bb7b992f491c43599ed5d
  file_picker: ^4.3.0
  firebase_auth: ^3.0.2
  firebase_core: ^1.7.0
  firebase_messaging: ^10.0.8
  firebase_storage: ^10.0.3
  flutter:
    sdk: flutter
  flutter_datetime_picker: ^1.5.1
  flutter_login: ^2.2.1
  flutter_onboard: ^1.0.3
  flutter_pdfview: ^1.2.2
  flutter_staggered_grid_view: ^0.4.0
  font_awesome_flutter: ^9.1.0
  get: ^4.3.8
  getwidget: ^2.0.4
  google_fonts: ^2.1.0
  google_nav_bar: ^5.0.5
  hb_check_code: ^0.0.2
  image_picker: ^0.8.4+2
  intl: ^0.17.0
  like_button: ^2.0.3
  line_icons: ^2.0.1
  material_floating_search_bar: ^0.3.6
  onesignal_flutter: ^3.3.0
  path: ^1.8.0
  path_provider: ^2.0.8
  random_string: ^2.3.1
  reactive_forms: ^10.6.2
  shared_preferences: ^2.0.8
  sliding_up_panel: ^2.0.0+1
  slugify: ^2.0.0
  syncfusion_flutter_pdfviewer: ^19.4.38-beta
  table_calendar: ^3.0.2
  translator: ^0.1.7
  url_launcher: ^6.0.12
dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.2.4

  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logoStore.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/logo.png
    - images/onboard1.png
    - images/onboard2.png
    - images/onboard3.png
    - images/onboard4.png
    - images/avatar1.png
    - images/avatar2.png
    - images/avatar3.png
    - images/avatar4.png
    - images/avatar5.png
    - images/avatar6.png
    - images/logoStore.png
    - images/avatar.png
    - images/workup.png
    - images/event1.jpeg
    - images/event2.jpeg
    - images/event3.jpeg
    - images/sampleLogo.png
    - images/cs.png
    - images/8.png
    - images/aposto.png
    - images/ist.png
    - images/kolektif.png
    - images/Loreal_logo.png
    - images/makromusıc.png
    - images/sabancı.png
    - images/sertf.png
    - images/swipe.png
    - images/workup.png
    - images/kvkk.pdf
    - images/ipa.jpg
    - images/cineshort.png
    - images/karavan.png
    - images/producter.png
    - images/evimdekipsikolog.png
    - images/suzer.png
    - images/bulbeez.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_native_splash:
  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  # flutter pub run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # flutter pub run flutter_native_splash:remove
  # color or background_image is the only required parameter.  Use color to set the background
  # of your splash screen to a solid color.  Use background_image to set the background of your
  # splash screen to a png image.  This is useful for gradients. The image will be stretch to the
  # size of the app. Only one parameter can be used, color and background_image cannot both be set.
  color: "#9077d1"
  #background_image: "images/logo.png"
  # Optional parameters are listed below.  To enable a parameter, uncomment the line by removing
  # the leading # character.
  # The image parameter allows you to specify an image used in the splash screen.  It must be a
  # png file and should be sized for 4x pixel density.
  #image: assets/splash.png
  # The color_dark, background_image_dark, and image_dark are parameters that set the background
  # and image when the device is in dark mode. If they are not specified, the app will use the
  # parameters from above. If the image_dark parameter is specified, color_dark or
  # background_image_dark must be specified.  color_dark and background_image_dark cannot both be
  # set.
  #color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png
  # The android, ios and web parameters can be used to disable generating a splash screen on a given
  # platform.
  #android: false
  #ios: false
  #web: false
  # The position of the splash image can be set with android_gravity, ios_content_mode, and
  # web_image_mode parameters.  All default to center.
  #
  # android_gravity can be one of the following Android Gravity (see
  # https://developer.android.com/reference/android/view/Gravity): bottom, center,
  # center_horizontal, center_vertical, clip_horizontal, clip_vertical, end, fill, fill_horizontal,
  # fill_vertical, left, right, start, or top.
  #android_gravity: center
  #
  # ios_content_mode can be one of the following iOS UIView.ContentMode (see
  # https://developer.apple.com/documentation/uikit/uiview/contentmode): scaleToFill,
  # scaleAspectFit, scaleAspectFill, center, top, bottom, left, right, topLeft, topRight,
  # bottomLeft, or bottomRight.
  #ios_content_mode: center
  #
  # web_image_mode can be one of the following modes: center, contain, stretch, and cover.
  #web_image_mode: center
  # To hide the notification bar, use the fullscreen parameter.  Has no affect in web since web
  # has no notification bar.  Defaults to false.
  # NOTE: Unlike Android, iOS will not automatically show the notification bar when the app loads.
  #       To show the notification bar, add the following code to your Flutter app:
  #       WidgetsFlutterBinding.ensureInitialized();
  #       SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom, SystemUiOverlay.top]);
  #fullscreen: true
  # If you have changed the name(s) of your info.plist file(s), you can specify the filename(s)
  # with the info_plist_files parameter.  Remove only the # characters in the three lines below,
  # do not remove any spaces:
  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'
  # To enable support for Android 12, set the following parameter to true.  Defaults to false.
  #android12: true
